### ISSUE TITLE
pacman error when installing hunit

### ISSUE THREAD

**Issue by gdmsl** [archhaskell/habs#164]
hunit is the fisrt package i've installed from this repo.

I've got this error both when installing and uninstalling:

```
(1/1) installing haskell-hunit                     [##########################] 100%
Reading package info from stdin ... done.
/tmp/alpm_0zoiXL/.INSTALL: line 8: /usr/share/doc/ghc/html/libraries/arch-gen-contents-index: No such file or directory
error: command failed to execute correctly
```

**Comment by kuerzn** [comment]
Many people could fall in this trap (I also just did). Would it make sense to make that dependency explicit? E.g. all haskell-core packages should depend on haskell-ghc which is 'provided' by the ghc version in haskell-core?

**Comment by magthe** [comment]
Feel free to add a comment about it to the instructions on the ArchLinux wiki.

**Comment by kuerzn** [comment]
Why not treat haskell-ghc as dependency?

**Comment by magthe** [comment]
Of course that's an option.  Feel free to submit a patch to `cblrepo` for it.
