### ISSUE TITLE
Arch repositories are down

### ISSUE THREAD

**Issue by lucacerone** [archhaskell/habs#176]
Dear all, the archaskell repositories seem to be down.

In my pacman.conf I had

```bash
[haskell-core]
Server = http://xsounds.org/~haskell/core/$arch
```

which worked just fine up to a few days ago.

Recently I have started getting the following error message when using pacman:

```bash
error: failed retrieving file 'haskell-core.db' from xsounds.org : Failed to connect to xsounds.org port 80: Connection refused
error: failed to update haskell-core (download library error)
```

I have tried both the repository mentioned in the Arch Wiki pages on Haskell, but I get the same error.
Is this a temporary thing or have the url changed for good?

Thanks a lot in advance for the help,

Cheers,
Luca

**Comment by HarryFromMarydelDE** [comment]
Same problem here trying to access repositories from Florida.

**Comment by muff1nman** [comment]
Also tried both repos. Same error.

**Comment by magthe** [comment]
Yes, it seems there's no httpd server running.  I'll try to get it restarted ASAP.

**Comment by ptrxyz** [comment]
Getting the same error:

error: failed retrieving file 'haskell-core.db' from xsounds.org : Failed to connect to xsounds.org port 80: Connection refused
error: failed retrieving file 'haskell-core.db' from www.kiwilight.com : Failed to connect to www.kiwilight.com port 80: Connection refused


Actually I quite often get that error. Is there a way to report them? Or is messages on github the preferred way to do that?

**Comment by outkaj** [comment]
I'm getting the same error. Thanks magthe for your attention to this.

**Comment by outkaj** [comment]
Repositories seem to be up for me now. Thanks!

**Comment by magthe** [comment]
Back up, so I'm closing this.

**Comment by NerdyProjects** [comment]
Again... Is there any mirror? I could not find one

**Comment by magthe** [comment]
@NerdyProjects I think there's a mirror, located in India IIRC. I think you'll have more luck finding the details if you use the mailing list <http://haskell.org/mailman/listinfo/arch-haskell> (or possible IRC, `#arch-haskell` on freenode).
