### ISSUE TITLE
xmonad and xmonad-contrib are missing.

### ISSUE THREAD

**Issue by euclio** [archhaskell/habs#177]
I can't find these packages in haskell-core.

**Comment by ouroboros8** [comment]
Same here.

**Comment by NicBallinger** [comment]
Same problem here. Xmonad, xmonad-contrib,  (and looking at the source)  pandoc have all been removed.

**Comment by magthe** [comment]
We're working on it: https://mail.haskell.org/pipermail/arch-haskell/2015-April/004819.html
