### ISSUE TITLE
'files' missing

### ISSUE THREAD

**Issue by daurnimator** [archhaskell/habs#181]
haskell-core is missing the `.files` index used by things like `pkgfile`:
```
warning: download failed: http://xsounds.org/~haskell/core/x86_64/haskell-core.files [error 404]
error: failed to update repo: haskell-core
```

**Comment by magthe** [comment]
I was fairly sure the invocation of `repo-add` I use was creating the `files` file, but apparently I was wrong.

**Comment by magthe** [comment]
This should be fixed now, for both architectures.
