### ISSUE TITLE
Another repo problem....

### ISSUE THREAD

**Issue by ptrxyz** [archhaskell/habs#184]
error: failed retrieving file 'haskell-core.db' from xsounds.org : Failed to connect to xsounds.org port 80: Connection refused.

Seems the repo is down again. This happens really frequently. Any way to avoid it?

**Comment by ptrxyz** [comment]
Repo seems to be back up again.

**Comment by ptrxyz** [comment]
Hm seems to be down again. 

error: failed retrieving file 'haskell-core.db' from xsounds.org : Connection timed out after 10000 milliseconds
error: failed retrieving file 'haskell-core.db' from www.kiwilight.com : Connection timed out after 10000 milliseconds

Whats the problem with this? Any chance I can mirror the repo somehow?

**Comment by magthe** [comment]
Unfortunately I don't have full access to the xsounds.org server and I can't fix it when it's down. I just wait a while and if the outage lasts for more than a day I send off an email to the person running it.

I think someone keeps a mirror, but I don't know the details of how to set it up. It's been discussed on the mailing list in the past so either have a look at the archives or just post a question there.

**Comment by shtrom** [comment]
It seems xsounds.org has been down for a few days again \:
