### ISSUE TITLE
GHC should rebuild the package registry.

### ISSUE THREAD

**Issue by orbifx** [archhaskell/habs#190]
If the `GHC` package is reinstalled, the Haskell package registry breaks. One solution then is to reinstall all Haskell packages, but it would be nice if that wasn't necessary.

Reinstalling `GHC` is not a regular thing to do, but it can happen.

**Comment by magthe** [comment]
I wonder if this could be done using hooks, now that `pacman` has them. Ideas and patches are most welcome!

**Comment by magthe** [comment]
Based on the level of interest I suggest this issue is closed as "won't fix".

**Comment by orbifx** [comment]
I can't label, so you best do it.
