### ISSUE TITLE
ghc-mod not in the haskell-core repository

### ISSUE THREAD

**Issue by SShrike** [archhaskell/habs#193]
It seems that ghc-mod is not in the package repository. Any chance it could be added?

**Comment by magthe** [comment]
`ghc-mod` was not buildable with ghc 7.10 for a long time. According to <https://github.com/kazu-yamamoto/ghc-mod/issues/437> it's fixed in the master branch, but still not released in a version on hackage.  As soon as it is I'll attempt to re-add it to the repo.

**Comment by 1nsanity** [comment]
@magthe Okay, thanks for the info!

**Comment by magthe** [comment]
Please feel free to help me keep an eye out for new releases upstream :)

**Comment by 1nsanity** [comment]
I'll make sure I keep an eye out ;)

**Comment by magthe** [comment]
There now seems to be a release that can handle 7.10 :)  <https://mail.haskell.org/pipermail/haskell-cafe/2015-August/120910.html>

**Comment by SShrike** [comment]
:+1:
