### ISSUE TITLE
Extremely slow installation - possibly an n^2 algorithm in haddock script

### ISSUE THREAD

**Issue by dbaynard** [archhaskell/habs#196]
Hello,

Haskell packages have always been really slow to install. The issue was the script which called haddock. When I upgraded my laptop, the first packages were pretty fast, but the more I installed, the slower it got.

If anyone wants more details (i.e. what command takes the time) I can find the information. I can reproduce it by reinstalling existing packages.

I believe the issue is with archhaskell, not haddock, as installing packages (with documentation) using stack doesn't cause the same trouble. I'm not sure whether this is the right place to post this. I'd be grateful for direction if not.

David

*Edit: See the problematic command in the next comment, below*

**Comment by dbaynard** [comment]
Here we go...

I used `ps aux | grep haddock` to view the precise command, and the output is below. Note that it is truncated to 4096 characters, as described [here](https://stackoverflow.com/questions/199130/how-do-i-increase-the-proc-pid-cmdline-4096-byte-limit).

```
root     25809  138  5.1 727568 420056 pts/4   Rl+  18:18   0:01 /usr/lib/ghc-7.10.2/bin/haddock
-B/usr/lib/ghc-7.10.2 -l/usr/lib/ghc-7.10.2 --gen-index --gen-contents -o /usr/share/doc/ghc/html/libraries -t Local Haskell Libraries -p /usr/share/doc/ghc/html/libraries/prologue.txt
-i /usr/share/doc/ghc/html/libraries/pipes-aeson,/usr/share/doc/ghc/html/libraries/pipes-aeson/pipes-aeson.haddock
-i /usr/share/doc/ghc/html/libraries/cmark,/usr/share/doc/ghc/html/libraries/cmark/cmark.haddock
-i /usr/share/doc/ghc/html/libraries/array-0.5.1.0,/usr/share/doc/ghc/html/libraries/array-0.5.1.0/array.haddock
-i /usr/share/doc/ghc/html/libraries/wai,/usr/share/doc/ghc/html/libraries/wai/wai.haddock
-i /usr/share/doc/ghc/html/libraries/monad-loops,/usr/share/doc/ghc/html/libraries/monad-loops/monad-loops.haddock
-i /usr/share/doc/ghc/html/libraries/hoogle,/usr/share/doc/ghc/html/libraries/hoogle/hoogle.haddock
-i /usr/share/doc/ghc/html/libraries/hourglass,/usr/share/doc/ghc/html/libraries/hourglass/hourglass.haddock
-i /usr/share/doc/ghc/html/libraries/case-insensitive,/usr/share/doc/ghc/html/libraries/case-insensitive/case-insensitive.haddock
-i /usr/share/doc/ghc/html/libraries/uuid-types,/usr/share/doc/ghc/html/libraries/uuid-types/uuid-types.haddock
-i /usr/share/doc/ghc/html/libraries/uuid,/usr/share/doc/ghc/html/libraries/uuid/uuid.haddock
-i /usr/share/doc/ghc/html/libraries/wai-logger,/usr/share/doc/ghc/html/libraries/wai-logger/wai-logger.haddock
-i /usr/share/doc/ghc/html/libraries/abstract-par,/usr/share/doc/ghc/html/libraries/abstract-par/abstract-par.haddock
-i /usr/share/doc/ghc/html/libraries/monad-logger,/usr/share/doc/ghc/html/libraries/monad-logger/monad-logger.haddock
-i /usr/share/doc/ghc/html/libraries/blaze-html,/usr/share/doc/ghc/html/libraries/blaze-html/blaze-html.haddock
-i /usr/share/doc/ghc/html/libraries/comonad,/usr/share/doc/ghc/html/libraries/comonad/comonad.haddock
-i /usr/share/doc/ghc/html/libraries/managed,/usr/share/doc/ghc/html/libraries/managed/managed.haddock
-i /usr/share/doc/ghc/html/libraries/haskeline-0.7.2.1,/usr/share/doc/ghc/html/libraries/haskeline-0.7.2.1/haskeline.haddock
-i /usr/share/doc/ghc/html/libraries/transformers-compat,/usr/share/doc/ghc/html/libraries/transformers-compat/transformers-compat.haddock
-i /usr/share/doc/ghc/html/libraries/cryptohash,/usr/share/doc/ghc/html/libraries/cryptohash/cryptohash.haddock
-i /usr/share/doc/ghc/html/libraries/optparse-applicative,/usr/share/doc/ghc/html/libraries/optparse-applicative/optparse-applicative.haddock
-i /usr/share/doc/ghc/html/libraries/conduit-extra,/usr/share/doc/ghc/html/libraries/conduit-extra/conduit-extra.haddock
-i /usr/share/doc/ghc/html/libraries/filemanip,/usr/share/doc/ghc/html/libraries/filemanip/filemanip.haddock
-i /usr/share/doc/ghc/html/libraries/void,/usr/share/doc/ghc/html/libraries/void/void.haddock
-i /usr/share/doc/ghc/html/libraries/cryptohash-conduit,/usr/share/doc/ghc/html/libraries/cryptohash-conduit/cryptohash-conduit.haddock
-i /usr/share/doc/ghc/html/libraries/io-choice,/usr/share/doc/ghc/html/libraries/io-choice/io-choice.haddock
-i /usr/share/doc/ghc/html/libraries/cipher-des,/usr/share/doc/ghc/html/libraries/cipher-des/cipher-des.haddock
-i /usr/share/doc/ghc/html/libraries/unix-compat,/usr/share/doc/ghc/html/libraries/unix-compat/unix-compat.haddock
-i /usr/share/doc/ghc/html/libraries/streaming-commons,/usr/share/doc/ghc/html/libraries/streaming-commons/streaming-commons.haddock
-i /usr/share/doc/ghc/html/libraries/vault,/usr/share/doc/ghc/html/libraries/vault/vault.haddock
-i /usr/share/doc/ghc/html/libraries/aeson-pretty,/usr/share/doc/ghc/html/libraries/aeson-pretty/aeson-pretty.haddock
-i /usr/share/doc/ghc/html/libraries/random,/usr/share/doc/ghc/html/libraries/random/random.haddock
-i /usr/share/doc/ghc/html/libraries/ghc-syb-utils,/usr/share/doc/ghc/html/libraries/ghc-syb-utils/ghc-syb-utils.haddock
-i /usr/share/doc/ghc/html/libraries/tagstream-conduit,/usr/share/doc/ghc/html/libraries/tagstream-conduit/tagstream-conduit.haddock
-i /usr/share/doc/ghc/html/libraries/async,/usr/share/doc/ghc/html/libraries/async/async.haddock
-i /usr/share/doc/ghc/ht
```

**Comment by magthe** [comment]
The script used for this can be found at <https://github.com/archhaskell/habs/blob/master/ghc/arch-gen-contents-index>.  Improvements are very welcome.

**Comment by dbaynard** [comment]
Great, thanks! I'll take a look.

**Comment by dbaynard** [comment]
As I understand it, this script gets called every time a package is installed, or upgraded. It indexes all the currently installed packages, in the context of the new one, and then rewrites the entire index. This is a lot of work, and is replicated _n_ times for _n_ packages. As there are _n_ packages already installed before the (_n_+1)th, this means the script is O(n^2).

There are a few options

* Only call `arch-gen-contents-index` at the end of all files being installed. Presumably there's a hook to run after pacman finishes installing all packages, although I haven't found it yet.
* Only read in the dependencies for `--gen-contents`, but read everything for `--gen-index`. This would probably have to work with the above fix, though. At least in this case, each package has its documentation installed after it is installed or upgraded.

What do you think?

**Comment by magthe** [comment]
@dbaynard Indeed, it's run on each installed package, and it's indeed inefficient.

1. I don't think `pacman` has support for hooks yet.  I may be wrong, so if that's available then that's the way to go!
2. I don't understand what you mean.  Do you mind putting together a script to illustrate so even I understand it?

**Comment by dbaynard** [comment]
1. OK, I'll investigate.
2. I think an example is easiest for me; hopefully the text after the jump will explain it.

Perhaps the process could be sped up a little by copying the interface files to /tmp and keeping them in ram for the whole pacman run. Depending on the installed size it could be ~100MB. I suspect this isn't the bottleneck, though.

There is another option: distribute a package including documentation and just regenerate the index after installation. I've read  https://github.com/archhaskell/habs/issues/192#issuecomment-109647512 and understand increasing compilation complexity can't be taken for granted.

---

Let's say I want to install `haskell-reflection`. The package installs, then runs the post_install hook.

This calls haddock with the `--gen-contents` flag, but not the `--gen-index flag`. The only haddock files supplied with the `-i` option are for the dependencies, in this case `base`, `tagged` and `template-haskell`. I assume this would be something like:

    haddock --gen-contents -o ${HADDOCK_DEST} -i .../base.haddock -i .../tagged.haddock -i .../template-haskell.haddock

Here haddock only needs to read three interface files.

This repeats for each package installed.

After pacman has finished installing packages, we run `haddock --gen-index` with all the interface files.

The difference here is that each package has its documentation installed after the package itself, rather than at the end. That may be an advantage. It may not.

**Comment by nponeccop** [comment]
See also https://github.com/magthe/cblrepo/issues/37

It's an issue with `cblrepo`, not with `archhaskell` as it merely uses whatever `cblrepo` generates for it.

**Comment by magthe** [comment]
@dbaynard two more questions:

1. How do we get the list of dependencies into `X.install`,  would `cblrepo` have to put that in there or is it something we can get out at install time?
2. You write

    > After pacman has finished installing packages, we run haddock --gen-index with all the interface files.

    Do you propose that as a manual step, or that we wait for `pacman` to gain support for hooks?

**Comment by dbaynard** [comment]
1. If we went with that option, I'd imagine `cblrepo` would be best placed to add dependencies to the install files, in addition to the PKGBUILD. I don't think this option is best, though.
2. Hooks would be best. Short of searching the `pacman` mailing list archive I can find one reference to `pacman` hooks online. I would search the archive but my impression from the roadmap is that we may be waiting quite a while.

---

I've had a little time over the long weekend to consider this, and the easiest approach might be to write a short programme, that simulates a post-transaction hook for `pacman`. Let's call it `hook`

`hook` does nothing when `pacman` is running, but as soon as `pacman` exits it calls (or executes the functions currently in) `arch-gen-contents-index`. Each habs package calls `hook` in its post-upgrade or post-install methods.

When called, `hook` ensures exactly one instance of `hook` is running.

`hook` might poll, say `ps`, to check whether `pacman` is running, or use `inotify` and the lock file used by `pacman` to run the hook when `pacman` releases the lock. Actually, the latter might not be a terrible option for `pacman` developers…

`hook` will be supplied either in the `ghc` package, or as a separate package as a dependency of ghc.

There are some desirable, but non-essential needs.

*   `hook` would ideally display text to the user, taking over in the same shell used by pacman. I wouldn't be able to implement this.
*   It should be possible to cancel `hook` and prevent installation of documentation.
*   If pacman fails, `hook` should exit.
*   Conversely, if `hook` fails, so should `pacman`

In addition, it would be useful if

*   to an end user it appeared that `pacman` had not completed until after `hook` completes.
*   `hook` were to work with alternatives to `pacman`

I'd probably be able to manage a simple version of the script, but I've never done systems level stuff before. Would `hook` inherit appropriate permissions to be able to edit the documentation files?

**Comment by magthe** [comment]
I think it's clear that the best option is to get support for hooks into `pacman`.  What you outline above might be possible, but it does feel like it could be a little shaky and brittle.  However, please do prove me wrong :)

**Comment by dbaynard** [comment]
I realised after I wrote that messages that I'd just described how to implement hooks for pacman... Luckily, this would only have to support arch linux users who have ghc installed. It's on my todo list (with the spec as written above).

Would you mark this issue as 'on hold' or equivalent, and I'll post back here when I have something?

**Comment by magthe** [comment]
With pacman 5.0 we apparently have hooks! Yay! I'd very much appreciate some help with working out how the hooks work and what they should look like for our use.

Maybe most importantly, can the hooking mechanism actually be used for what we want to do?

**Comment by magthe** [comment]
I'm now working on this. I have a version of a hook that seems to work, but I also need to make some changes to *cblrepo* and of course rebuild *all* packages, so it takes a little while to get through it.
