### ISSUE TITLE
Reflection package release decreased rather than increased

### ISSUE THREAD

**Issue by dbaynard** [archhaskell/habs#197]
Hello,

`haskell-reflection` has gone from version `2_0-2` to `2_0-1`. It's easily fixable by removing the offending packages and reinstalling, but not ideal.

```
> pacman -Qi haskell-reflection
Name           : haskell-reflection
Version        : 2_0-2
Description    : Reifies arbitrary terms into types that can be reflected back into terms
Architecture   : x86_64
URL            : http://github.com/ekmett/reflection
Licences       : BSD3
Groups         : None
Provides       : None
Depends On     : ghc=7.10.2-1
Optional Deps  : None
Required By    : haskell-lens
Optional For   : None
Conflicts With : None
Replaces       : None
Installed Size :   5.36 MiB
Packager       : Unknown Packager
Build Date     : Thu 30 Jul 2015 12:28:49 BST
Install Date   : Mon 24 Aug 2015 12:13:43 BST
Install Reason : Installed as a dependency for another package
Install Script : Yes
Validated By   : Signature
```

```
> pacman -Si haskell-reflection
Repository     : haskell-core
Name           : haskell-reflection
Version        : 2_0-1
Description    : Reifies arbitrary terms into types that can be reflected back into terms
Architecture   : x86_64
URL            : http://github.com/ekmett/reflection
Licences       : BSD3
Groups         : None
Provides       : None
Depends On     : ghc=7.10.2-1
Optional Deps  : None
Conflicts With : None
Replaces       : None
Download Size  : 367.22 KiB
Installed Size : 5557.00 KiB
Packager       : ArchHaskell <arch-haskell@haskell.org>
Build Date     : Tue 25 Aug 2015 23:18:54 BST
Validated By   : MD5 Sum  SHA256 Sum  Signature
```

**Comment by dbaynard** [comment]
Also, `haskell-lens` was upgraded silently (i.e. without an increase in the pkgrel, at `4.12.3_0-1`)

**Comment by magthe** [comment]
I'll bump the `pkgrel` of those packages for you.

Note though that it's a bit strange, because both of those packages were *added* to `[haskell-core]` just two days ago.  Also, if you have a look at the *Packager* field of your `haskell-reflection` it's not the same as for the package from `[haskell-core]`.  This makes me pretty sure the package you have on your system doesn't come from `[haskell-core]` at all.

**Comment by dbaynard** [comment]
Consider it strange no longer! Both `lens` and `reflection` were moved from [haskell-happstack] to [haskell-core] . Commits tensor5/haskell-happstack@f69285858d56c9ac3b6da9bce02e6608ca9256ae and e083214795d2d3361d3caaec52183219f090f11d show the issue.

Thanks, @magthe
