### ISSUE TITLE
ghc broken due to upgrade of ncurses

### ISSUE THREAD

**Issue by bjin** [archhaskell/habs#202]
`ncurses` upgraded to 6.0 recently, `ghc` package need to be recompiled against it.

**Comment by vlatkoB** [comment]
Just installed `ghc` with `stack setup`.

**Comment by bjin** [comment]
@vlatkoB  It won't work as well, `stack`  uses official GHC builds, and they are built against `libtinfo.so.5`.

**Comment by bjin** [comment]
Ooops. I realized that archhaskell just use the official compiled binary. Closing since it's unlikely to be fixed easily.

**Comment by vlatkoB** [comment]
@bjin Downgrading `ncurses` is a VERY bad idea. As I read while searching for solution, `bash` depends on it, stops working and no login possible after!

**Comment by bjin** [comment]
Yes, I understand. I will probably compile GHC myself.

**Comment by carlostome** [comment]
You just need to clone this repo, cd into the ghc subfolder and use makepkg. Then you can install it using pacman -U.

**Comment by vlatkoB** [comment]
`ghc` and `cabal` installed with `stack`seem to work correctly, but I'm getting strange error on some recompiled apps (`ghci-ng`)
```bash
/usr/lib/ghc-7.10.2/settings: openFile: does not exist (No such file or directory)
```

Any idea?

**Comment by LeifW** [comment]
I don't think this ticket should be closed - ghc in [haskell-core] needs to be recompiled against the new ncurses before it will work again. In the meantime, I suppose you can compile ghc yourself, or use the one in [extra].

**Comment by LeifW** [comment]
@vlatkoB That file is owned by the ghc 7.10.2-1 package I installed from [haskell-core].

**Comment by bjin** [comment]
I closed it since I made a wrong assumption, reopen it.

**Comment by LeifW** [comment]
A workaround in the meantime, mentioned in the #archlinux-haskell IRC channel:
You should still have the old ncurses package in /var/cache/pacman/pkg. Downgrading to it can be dangerous, unless you also downgrade all the other packages that were upgraded with it at the same time (bash, vim, etc). But you can have version 5 of ncurses file ghc is linked against alongside version 6 in /usr/lib; they have different filenames.
What I did:
* Extracted the contents of the old package w/ `tar xJvf`
* Copied the `libncursesw.so.5.9` file in there to `/usr/lib/libncursesw.so.5`

**Comment by vlatkoB** [comment]
@LeifW Dont understand what you mean. Can you explain?

I symlinked `lib/ghc-7.10.2/` from `.stack` to `/usr/lib/ghc-7.10.2/` and all works now.
Also, had to symlink `ghc-pkg` because `haskell-mode` in `emacs` seaches it in `/usr/bin`. Didn't have time to investigate more.

**Comment by magthe** [comment]
A symbolic link `libncursesw.so.5` to `libncursesw.so.6` seems to make GHC happy enough to be a workaround until I finish a complete rebuild of all packages.

**Comment by menelaos** [comment]
Can you make a rough estimate as to how long that will probably take (hours, a few days, around Christmas? :-)) Thanks for your work!
