### ISSUE TITLE
Failed to install Haddock

### ISSUE THREAD

**Issue by jvican** [archhaskell/habs#203]
Just added haskell-core to my pacman.conf. I updated cache and installed `ghc cabal-install haddock alex happy`.I got an error when installing Haddock. That operation installed `ghc 7.10.2` whereas `haddock` and `haskell-haddock-library` depend on a different version of `ghc 7.10.1`.

__Error message__:
`warning: cannot resolve "ghc=7.10.1", a dependency of "haddock"
warning: cannot resolve "ghc=7.10.1", a dependency of "haskell-haddock-api"`

**Comment by magthe** [comment]
That is most likely caused by the placement of the *haskell-core* repo in your `pacman` config -- you are most likely picking up the package from *community*.  Move *haskell-core* up, it needs to be above *extra*, as is explained on the wiki page: <https://wiki.archlinux.org/index.php/ArchHaskell#.5Bhaskell-core.5D>

**Comment by jvican** [comment]
I followed the instructions carefully, my repo is above extra as it's required. Same error still. Nothing works, neither removing manually the packages from the cache. Any idea?

**Comment by jvican** [comment]
Installing ghc 7.10.2-2 first, haddock gives me these warnings:
`:: haskell-ghc-paths: requires ghc=7.10.2-2
:: haskell-haddock-library: requires ghc=7.10.2-2`

Which is very weird, because that version is already installed. If I now install `haskell-ghc-paths` and `haskell-haddock-library`, the same warning appear, as if it is ignoring the fact that those packets are already installed.

**Comment by magthe** [comment]
Yes, very weird indeed.  All I can say, without having direct access to your systems, is that everything seems correct on the *haskell-core* side and that it works fine for me.

Have you tried starting over, i.e. running `pacman -Rncs ghc` and then installing the packages you want again?

**Comment by jvican** [comment]
Yes, I've tried almost everything. This is interesting, it looks like the Haddock package is not in haskell-core repo:
`haskell-core/haskell-haddock-library 1.2.1_0-3
    Library exposing some functionality of Haddock.
  
community/haddock 2.16.1-2
    Tool for generating documentation for Haskell libraries
  
community/haskell-haddock-api 2.16.0-2
    A documentation-generation tool for Haskell libraries
  
community/haskell-haddock-library 1.2.0-2
    A documentation-generation tool for Haskell libraries
  
`
Is this true? Why?

**Comment by magthe** [comment]
Haddock is in `ghc`.  It's distributed as part of `ghc` in order to build the documentation for `ghc` itself.  It's also installed as part of of `ghc`'s `make install`, and I've simply opted to leave it there.

**Comment by jvican** [comment]
That explains everything. Thanks for the support!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Magnus TherningSent: Friday, September 25, 2015 13:38To: archhaskell/habsReply To: archhaskell/habsCc: JorgeSubject: Re: [habs] Failed to install Haddock (#203)Haddock is in ghc.  It's distributed as part of ghc in order to build the documentation for ghc itself.  It's also installed as part of of ghc's make install, and I've simply opted to leave it there.

—Reply to this email directly or view it on GitHub.
