### ISSUE TITLE
Request: Ghci-mod

### ISSUE THREAD

**Issue by jvican** [archhaskell/habs#204]
[Ghci-mod](https://hackage.haskell.org/package/ghc-mod) is very handy for text-editors plugins such as [neovim-ghcimod](https://github.com/neovimhaskell/neovim-ghcmod).

**Comment by LeifW** [comment]
ghc-mod is already in habs. There is no such thing as ghci-mod, as far as I know? ghc-mod includes a ghc-modi binary as well, but it's deprecated in favor of 'ghc-mod legacy-interactive'
