### ISSUE TITLE
Work together on [community] haskell packages

### ISSUE THREAD

**Issue by felixonmars** [archhaskell/habs#206]
Hi,

Within the past few days I added pandoc/shellcheck and their dependencies to the [community] repository with the help of your amazing cblrepo tool. I have to say thank you first!

I would like to discuss about possibilities to work together and merge the whole [archhaskell] repo into [community]. Since Vesa and Thomas's resignation, we don't have a haskell maintainer now. I am still new to haskell, and I would like to help, but I think it would be much better to have haskell enthusiasts like you. There are 126 haskell-\* packages in the [community] repo right now, and there are also tools like pandoc, xmonad, etc, and most of them are also in the archhaskell repo. By working together we would be able to avoid duplication of efforts in the future.

Hope you like the idea :)

**Comment by magthe** [comment]
Nice to hear you like *cblrepo*.  Do you use it for all the Haskell packages in `[community]`?

I hadn't noticed Vesa and Thomas had left.  They had some ideas of where to take the Haskell support in Arch, IIRC they wanted to limit the packages to the minimal (basically *cabal-install* and what was necessary to build it).  I'm guessing that didn't quite work out though and that you aren't really interested in keeping the number of packages to a minimum ;)

A few things to consider:

- Upgrades of *ghc* often leave a large number of packages unbuildable for a long time (e.g. *ghc-mod* was unbuildable with 7.10 for about 6 months).  What are the options for handling that kind of situations with packages in `[community]`?
- *ghc* is in [extra], do you have the ability to upload new versions of it?

**Comment by felixonmars** [comment]
Yes, I used it for all the Haskell packages in `[community]` with some minor changes. And yes, I don't really want to keep the number of packages to a minimum as long as they have maintainers :)

And to the two questions:

- We can offer an old ghc in the repos temporarily for the transition period, just like how we handle `lua`, `lua52` and `lua51` at the moment. Or if the packages need to be present on a same registry, maybe we can delay the ghc bump for a bit. And if the package is not very important, we can also just bump ghc and drop it to AUR until it builds. This is how we handle similar situations like the Python 3.5 bump recently (we dropped kdevelop-python to AUR and waiting for upstream to support the new Python).
- Yes, and if you would want to join the TU team, we can move it and also `cabal-install` to `[community]`, too.

**Comment by magthe** [comment]
The possibility to kick packages to AUR until they build properly is a rather nice way of dealing with the particular issue of upstream not moving as fast as we'd like :)

It's good that also *ghc* is under your control!

**Comment by dkasak** [comment]
@felixonmars, just chiming in about an issue I recently had that is related to this. pandoc is a really useful tool in itself, regardless of its Haskell heritage, so I was rather disappointed to find out that your package also contains pandoc libraries and registers it as a GHC package as well. Due to the way GHC packages work, I strive to have a minimal number of packages registered in my global GHC package database since Haskell development quickly becomes unfeasible otherwise. Registering pandoc as a GHC package then prevents me from using your package if I simply need pandoc, the tool. It also makes for a large amount of unnecessary clutter for non-haskellers who might want to use it (since it depends on ghc and whatnot). I think this conflation of tool and its development libraries/language with Haskell in Arch is unfortunate; after all, the docker doesn't depend on the Go compiler.

I ask you to consider packaging useful/popular tools written in Haskell (I only have pandoc in mind for the time being) as simple, ready-to-use, statically-linked binaries and only include the full-blown library version in a separate Arch package. Would this be possible?

**Comment by felixonmars** [comment]
I am actually not familiar enough with static linked executables. The pandoc package in [community] comes from the haskell-pandoc package in [haskell-core], and I really need some instructions on how to provide the static one correctly. Any hints @magthe ?

**Comment by lilydjwg** [comment]
@felixonmars you just need to seperate the `pandoc` binary and resource files with all those Haskell things (.so, .hi, .p_hi, .dyn_hi, API docs, etc).

**Comment by magthe** [comment]
@dkasak  Sure, it's possible, but I still haven't looked at implementing support for it in the tool used for packaging an maintaining.

**Comment by felixonmars** [comment]
OK. I have updated darcs and shellcheck to drop the libraries (and their docs). I'll try to play with pandoc tomorrow.

**Comment by LeifW** [comment]
What about patching the PKGBUILD to add a `rm -r ${pkgdir}/usr/lib`, like https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=idris#n27 ?

**Comment by magthe** [comment]
I have some split builds of *pandoc* and friends in the testing repo now.  Let me know if they are any good and I'll put them into core:

```
[haskell-testing]
Server = http://xsounds.org/~haskell/testing/$arch
```

**Comment by dkasak** [comment]
@magthe, xsounds.org looks down from here.

**Comment by magthe** [comment]
Yupp, it looks down from here too... it was up earlier today though.  Let's wait and see if it comes back during the day.

**Comment by magthe** [comment]
@dkasak It looks like it's back up now.  Let me know if you try out the packages and run into any issues.

**Comment by dkasak** [comment]
@magthe I tried haskell-pandoc-tool and it seems to be working great. Thanks!

**Comment by magthe** [comment]
@dkasak Good to hear. In general I follow the old "no news is good news", i.e. no complaints means it's working ;)  It's however always nice to get confirmations too.

**Comment by magthe** [comment]
This discussion has lingered here for long enough. I'm closing it.
