### ISSUE TITLE
zlib >= 0.6.1 segfaults GHC 7.10.2 from Agda and Idris

### ISSUE THREAD

**Issue by LeifW** [archhaskell/habs#207]
Issues for each: https://github.com/agda/agda/issues/1518, https://github.com/idris-lang/Idris-dev/pull/2433. Turns out apparently be a GHC runtime bug: https://ghc.haskell.org/trac/ghc/ticket/10904. Fixed in GHC 7.10.3 (if it's ever released).
Or maybe there'll be a new zlib release that'll work around that?

You can build Idris and Agda currently by constraining zlib to be < 0.6.1. Unfortunately, that means they can't build against habs. Plenty of other stuff in habs has been built against zlib 0.6.1.1; I'm assuming they haven't been reporting segfaults. I can't think of a very tenable option for downgrading zlib in habs at this point. Wish this had been caught sooner.

Stackage seems to be blocking the upgrading on zlib 0.6 on things like this; not sure if we wanted to align with them - there was that related issue.

**Comment by magthe** [comment]
Well, this is a case where a version of a package we do include causes a package we *don't* include to crash.  I'm not sure what we could ever do about that short of trying to pull in all of Hackage.

Stackage seems to include Agda, and they have the computing power to build and run all test suites.  Neither is true for *habs*.

Aligning with Stackage is of course an option, but it would require a bit of work to get there.  I'm also not convinced the loss of freedom is worth it.
