### ISSUE TITLE
makeahpkg fails with Trapped ERR

### ISSUE THREAD

**Issue by wad209** [archhaskell/habs#208]
I am trying to build all of habs as per your instructions in README.md. Here is the output of what happens with a fresh git repository: https://pastee.org/2hxq3 (I omitted all the pacman output to keep it short, I can provide if needed). For those too lazy to look at the pastee, the error is:

./makeahpkg: line 69: _ver: unbound variable
*** ERROR: Trapped ERR, something went very wrong.

This used to work but I think the issues occurred when bash was upgraded, though I can't be certain this was the cause. Is anybody else having this issue?

Edit: I should add that this DID work at one time on this machine.

**Comment by wad209** [comment]
I should confirm that I DID have this working sometime in the past, and it no longer works.

**Comment by magthe** [comment]
I don't think that has anything to do with the update to `bash`, it seems more likely it's due to changes in the generated `PKGBUILD`s.

Maybe this is a good time to push the Docker-based build scripts I've been using lately.

**Comment by wad209** [comment]
That would be great! Let me know if you would like me to pastebin some of the outputted PKGBUILDs.

**Comment by magthe** [comment]
How is it working out?

**Comment by wad209** [comment]
Works great! You might make a note of the newly required deps but other than that I am now able to build packages! Thanks!
