### ISSUE TITLE
Missing MissingH

### ISSUE THREAD

**Issue by tensor5** [archhaskell/habs#210]
The package `haskell-missingh-1.3.0.1_0-15-i686.pkg.tar.xz` is present on [xsounds](http://xsounds.org/~haskell/core/i686/) but has not been added to the database (still on release 14).

Thanks

**Comment by magthe** [comment]
This was fixed with <https://github.com/archhaskell/habs/commit/b0ba686312a032a313392472aa1c6e5dfa184d4e>.
