### ISSUE TITLE
New GHC version conflicts

### ISSUE THREAD

**Issue by parnmatt** [archhaskell/habs#218]
There seems to have been some packages missed. When trying to upgrade, I cannot due to explicit dependencies that have not had updated PKGBUILDS.
```
error: failed to prepare transaction (could not satisfy dependencies)
:: haskell-djinn-ghc: installing ghc (8.0.1-1) breaks dependency 'ghc=7.10.3-3'
:: haskell-djinn-ghc: installing haskell-async (2.1.0_0-250) breaks dependency 'haskell-async=2.1.0_0-3'
:: haskell-djinn-ghc: installing haskell-mtl (2.2.1_1-250) breaks dependency 'haskell-mtl=2.2.1_1-4'
:: haskell-djinn-lib: installing ghc (8.0.1-1) breaks dependency 'ghc=7.10.3-3'
:: haskell-djinn-lib: installing haskell-mtl (2.2.1_1-250) breaks dependency 'haskell-mtl=2.2.1_1-4'
:: haskell-fclabels: installing ghc (8.0.1-1) breaks dependency 'ghc=7.10.3-3'
:: haskell-fclabels: installing haskell-mtl (2.2.1_1-250) breaks dependency 'haskell-mtl=2.2.1_1-4'
```

**Comment by magthe** [comment]
Yupp, that's due to me not having built all packages for 8.0.1. So, totally expected. This time around I focused on getting tools packages (stack, pandoc, xmonad, etc) so packages that aren't dependencies of those tools have disappeared.

**Comment by tuxayo** [comment]
It took me some time to understand so I post this for others:
The fix is to remove the packages that have dependency issues, here we would do 
`pacman -Rdd haskell-djinn-ghc haskell-djinn-lib haskell-fclabels`

And then update the whole system.
