### ISSUE TITLE
Current breakage caused by `haskel-core` packages

### ISSUE THREAD

**Issue by johannesgerer** [archhaskell/habs#221]
> @magthe on #192
> 
> > @johannesgerer
> >    Running sudo pacmatic -Syyu --noconfirm today gives the following errors. I currently do not no the root of the problem, but this kind of error never occurs in core/community/extra.
> 
> The root of the problem is simple. Yesterday I moved all packages from haskell-testing over to haskell-core, and since I have only built about 275 of the packages there will be some breakage. There were about 100 packages that didn't make it across this time.

If you find the time, it would be great to really understand what went wrong and why building the remaining 100 packages now would not solve the current  `pacman -Syu` problem.

And also, what manual steps would I have to take, to fix this on my side...

I do not really understand, what exactly is going wrong here

```
warning: haskell-uuid: local (1.3.12_0-1) is newer than community (1.3.12-8)
```

Does pacman think my local uuid packge is newer than the community version and is thus refusing to update it? This does not seem to be intenden behavior (maybe it is caused by the `_0` in the version string of the ArchHaskell package?

**Comment by magthe** [comment]
- Building the remaining 100 packages would indeed solve the problem.
- You can fix it on your side by removing the packages that are holding back the upgrade.
- What's going on is that the installed `haskell-uuid` version, which is found only locally, is newer than the newest version available in a repo (in `[community]`). You can verify this using the `vercmp` utility that comes with the `pacman` package.
